-- 001 — accounts and sessions.
--
-- Portable subset only (planning/01 §3.1): TEXT / BIGINT / INTEGER, which mean the same
-- thing in SQLite and Postgres. No TIMESTAMP (time zone semantics differ), no BOOLEAN
-- (SQLite has none), no SERIAL (ids are generated by the application).
--
-- Timestamps are epoch milliseconds. BIGINT, not INTEGER: epoch ms is ~1.7e12 and would
-- overflow a 32-bit Postgres INTEGER.

CREATE TABLE account (
  id             TEXT   PRIMARY KEY,
  username       TEXT   NOT NULL,
  -- Case-insensitive uniqueness as a plain unique index, rather than COLLATE NOCASE
  -- (SQLite-only) or CITEXT (Postgres-only).
  username_lower TEXT   NOT NULL UNIQUE,
  password_hash  TEXT   NOT NULL,
  -- Reserved for the single-use recovery code (planning/07 §2, Q16). The flow is not
  -- implemented yet; the column exists so adding it later is not a migration of live data.
  recovery_hash  TEXT,
  created_at     BIGINT NOT NULL,
  last_seen_at   BIGINT NOT NULL,
  deleted_at     BIGINT
);

CREATE TABLE session (
  -- The SHA-256 of the opaque token, never the token itself. A database leak must not
  -- hand out live sessions.
  token_hash   TEXT    PRIMARY KEY,
  account_id   TEXT    NOT NULL REFERENCES account(id),
  created_at   BIGINT  NOT NULL,
  expires_at   BIGINT  NOT NULL,
  last_used_at BIGINT  NOT NULL,
  -- 0/1. Whether this is a "keep me logged in" session, which slides on use.
  remember     INTEGER NOT NULL DEFAULT 0,
  user_agent   TEXT
);

CREATE INDEX idx_session_account ON session (account_id);
CREATE INDEX idx_session_expires ON session (expires_at);
